@startuml mainframe

package front {
    class ui {
        + runUi()
    }
}

package back {
    package inter {
        interface IModule {
            + void init()
        }

        interface IGetSignal {
            + getValue(double time) -> SignalData&
        }
        IModule *-- IGetSignal

        interface ICalculationBase {
            + void run()
        }

        interface ICalculation<class TaskType> {
            + addTask(TaskType task)
            + clear()
        }
        ICalculation ..|> ICalculationBase
        IModule *-- ICalculation

        interface ICalculationTask<class In> {
            + addEntry(In& in)
            + run()
        }
        ICalculation *-- ICalculationTask
    }

    package base {
        class BaseWave {
            - double frequency_
            - double amplitude_
            - BaseWaveStatus status_
            + override init()
            + getValue() -> SignalData
        }
        BaseWave <|.. IModule
        BaseWave <|.. IGetSignal

        class BaseWaveStatus {
            - SignalDataBuffer values_
            - SignalData omega_
            + static update(vector<Self*> source, vector<SignalDataBuffer> data)
            + getLocation() -> size_t
            + iteration()
            + calibrate()
        }
        BaseWave *-- BaseWaveStatus

        class BaseWaveCalculation<BaseWaveCalculationTask> {
            - vector<BaseWaveCalculationTask> tasks_
            + override run()
            + override addTask(BaseWaveCalculationTask task)
            + override clear()
        }
        BaseWave *-- BaseWaveCalculation
        BaseWaveCalculation ..|> ICalculation

        class BaseWaveCalculationTask<BaseWaveStatus> {
            - vector<BaseWaveStatus*> source_
            - array<SignalDataBuffer, 2> data_
            - size_t step_count_
            + override addEntry(BaseWaveStatus& in)
            + override run()
            + step()
        }
        BaseWaveCalculationTask ..|> ICalculationTask 
        BaseWaveCalculation *-- BaseWaveCalculationTask
        BaseWaveCalculationTask -- BaseWaveStatus
    }

    package core {
        class Calculator {
            - vector<ICalculationBase*> calculations_
            + registerCalculater(ICalculationBase* item)
            + run()
        }
        Calculator -- ICalculation

        class Tasker {
            - size_t step_count_
        }
        Tasker *-- ICalculationTask

        class Environment {
            - vector<Tasker> tasker_
            - vector<IGetSignal*> signals_
        }
        Environment *-- Tasker
        Environment *-- IGetSignal

        class Workspace {
            - vector<Environment> envs_
            - vector<IModule> modules_
        }
        Workspace *-- Environment
        Workspace *-- IModule

        class Session {
            - Calculator calculator_
            - vector<Environment> envs_
        }
        Session *-- Environment
        Session *-- Calculator
    }

    package data {
        class SignalData {
            - double I
            - double Q
        }

        class SignalDataBuffer {
            - vector<double> Is
            - vector<double> Qs
            + replace(size_t index, SignalData& data)
            + pushBack(SignalData& data)
        }
        SignalDataBuffer -- SignalData
    }

    package conf {
        class Config {}
    }

    package io {}
    package log {}
    package draw {}
    package arg {}
}

@enduml