name: Build UML

on:
  push:
    paths:
      - docs/*.puml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install Java
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: temurin

      - name: Download Plant UML
        run: wget -q https://github.com/plantuml/plantuml/releases/latest/download/plantuml.jar

      - name: Generate SVG
        run: java -jar plantuml.jar -tsvg docs/*.puml

      - name: Commit SVG
        run: |
          git config --global user.name "Ecliptic ISET ( Bot )"
          git config --global user.email "ecliptic@ratiset.org"
          git add docs/*.svg
          git commit -m "docs(uml): Build the SVG"
          git push